import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  target: 'node22',
  external: [
    '@semilayer/core',
    '@semilayer/bridge-postgres',
    '@semilayer/bridge-mysql',
    '@semilayer/bridge-sqlite',
    '@semilayer/bridge-mssql',
    '@semilayer/bridge-cockroachdb',
    '@semilayer/bridge-neon',
    '@semilayer/bridge-turso',
    '@semilayer/bridge-planetscale',
    '@semilayer/bridge-d1',
    '@semilayer/bridge-supabase',
    '@semilayer/bridge-mongodb',
    '@semilayer/bridge-firestore',
    '@semilayer/bridge-redis',
    '@semilayer/bridge-upstash',
    '@semilayer/bridge-dynamodb',
    '@semilayer/bridge-elasticsearch',
    '@semilayer/bridge-cassandra',
    '@semilayer/bridge-clickhouse',
    '@semilayer/bridge-bigquery',
    '@semilayer/bridge-duckdb',
    '@semilayer/bridge-snowflake',
    '@semilayer/bridge-mariadb',
    '@semilayer/bridge-oracle',
  ],
})
